name: CMake

on:
  push:
    branches: [ "main" ]

env:
  build_directory: ${{github.workspace}}/BUILD
  build_type: Release
  release_name: build_${{github.run_number}}

jobs:
  build:
    strategy:
      matrix:
        platform: [Win32]
        
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{env.build_directory}} -G "Visual Studio 17 2022" -A ${{matrix.platform}} -DCMAKE_BUILD_TYPE=${{env.build_type}} -DREDUMPER_VERSION_BUILD=${{github.run_number}}

    - name: Build
      run: cmake --build ${{env.build_directory}} --config ${{env.build_type}}
      
    - name: Test
      working-directory: ${{env.build_directory}}
      run: ctest -C ${{env.build_type}}

    - name: Package
      working-directory: ${{env.build_directory}}
      run: cpack -G ZIP --config CPackConfig.cmake

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.release_name}}
        path: ${{env.build_directory}}/redumper-*.zip
        
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download
        uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{env.release_name}}
      
      - name: 'Release'
        shell: bash
        run: |
          hub release create ${{ env.release_name }} -m ${{ env.release_name }}
          for f in redumper-*.zip; do hub release edit ${{ env.release_name }} -m ${{ env.release_name }} -a $f; done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
