name: CMake

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - '**'
#  pull_request:
#    branches: [ "main" ]

env:
  build_directory: ${{github.workspace}}/BUILD
  build_type: Release
  release_name: build_${{github.run_number}}

jobs:
  build:
    strategy:
      matrix:
        platform: [Win32]
        
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{env.build_directory}} -G "Visual Studio 17 2022" -A ${{matrix.platform}} -DCMAKE_BUILD_TYPE=${{env.build_type}} -DREDUMPER_VERSION_BUILD=${{github.run_number}}

    - name: Build
      run: cmake --build ${{env.build_directory}} --config ${{env.build_type}}
      
    - name: Test
      working-directory: ${{env.build_directory}}
      run: ctest -C ${{env.build_type}}

    - name: Package
      working-directory: ${{env.build_directory}}
      run: cpack -G ZIP --config CPackConfig.cmake

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.release_name}}
        path: ${{env.build_directory}}/redumper-*.zip

#    - name: Release
#      uses: softprops/action-gh-release@v1
#      with:
#        tag_name: BUILD
#        files: ${{github.workspace}}/build.${{matrix.platform}}/redumper-*.zip

#    - name: GitHub Release
#      run: hub release create ${{ env.release_name }} -m ${{ env.release_name }}
#        hub tag ${{ env.release_name }}
#        hub push origin ${{ env.release_name }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
#    - name: GitHub Release 2
# use hub release show build_28 and check output
#      continue-on-error: true
#      run: hub release create ${{ env.release_name }} -m ${{ env.release_name }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        id: download
        with:
          name: ${{env.release_name}}
      
      - name: Display structure of downloaded files
        run: ls -R

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

